// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb240M5bOTHr1yQ3aj5VPq3gUKcuDQz5E',
    appId: '1:166151924801:web:a000436b15a622e0616ac0',
    messagingSenderId: '166151924801',
    projectId: 'spaces-8eafc',
    authDomain: 'spaces-8eafc.firebaseapp.com',
    storageBucket: 'spaces-8eafc.firebasestorage.app',
    measurementId: 'G-N8HM8JBZNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArUkxTw5XKHeZgIFc1jczxQR_NiOLC8QM',
    appId: '1:166151924801:android:541a3817d2e2b1e9616ac0',
    messagingSenderId: '166151924801',
    projectId: 'spaces-8eafc',
    storageBucket: 'spaces-8eafc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0BGF2VFp0clNq4UEeqRKp_OQICP6YcPE',
    appId: '1:166151924801:ios:0b88a907a599f725616ac0',
    messagingSenderId: '166151924801',
    projectId: 'spaces-8eafc',
    storageBucket: 'spaces-8eafc.firebasestorage.app',
    iosBundleId: 'com.example.spaces',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0BGF2VFp0clNq4UEeqRKp_OQICP6YcPE',
    appId: '1:166151924801:ios:0b88a907a599f725616ac0',
    messagingSenderId: '166151924801',
    projectId: 'spaces-8eafc',
    storageBucket: 'spaces-8eafc.firebasestorage.app',
    iosBundleId: 'com.example.spaces',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb240M5bOTHr1yQ3aj5VPq3gUKcuDQz5E',
    appId: '1:166151924801:web:49978260491371e5616ac0',
    messagingSenderId: '166151924801',
    projectId: 'spaces-8eafc',
    authDomain: 'spaces-8eafc.firebaseapp.com',
    storageBucket: 'spaces-8eafc.firebasestorage.app',
    measurementId: 'G-570XJZFS8Y',
  );
}
